### ISSUE TITLE
Console fails to start because of jetty-gzip

### ISSUE THREAD

**Issue by lorthirk** [eclipse/kapua#374]
It seems that after merging 0c8d1a912f6ce4fac6b516a6390234a5e4077084 the console is failing to start because of jetty-gzip:

```
10:31:52,777 [main] INFO  EnvironmentLoader:128  - Starting Shiro environment initialization.
10:31:52,914 [main] INFO  AuthorizingRealm:248  - No cache or cacheManager properties have been set.  Authorization cache cannot be obtained.
10:31:52,914 [main] INFO  IniSecurityManagerFactory:112  - Realms have been explicitly set on the SecurityManager instance - auto-setting of realms will not occur.
10:31:52,916 [main] INFO  EnvironmentLoader:141  - Shiro environment initialized in 135 ms.
Starting Jetty on port 8889
   [WARN] failed jetty-gzip: java.lang.NoClassDefFoundError: javax/servlet/AsyncListener
   [WARN] failed com.google.gwt.dev.shell.jetty.JettyLauncher$WebAppContextWithReload@22b53226{/,/Users/claudio.mezzasalma/Projects/sources/eclipse/kapua/console/target/console}: java.lang.NoClassDefFoundError: javax/servlet/AsyncListener
   [WARN] failed RequestLogHandler@1fcb4808: java.lang.NoClassDefFoundError: javax/servlet/AsyncListener
   [WARN] Error starting handlers
java.lang.NoClassDefFoundError: javax/servlet/AsyncListener
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at org.mortbay.jetty.servlet.Holder.newInstance(Holder.java:153)
	at org.mortbay.jetty.servlet.FilterHolder.doStart(FilterHolder.java:92)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:593)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1220)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:513)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:448)
	at com.google.gwt.dev.shell.jetty.JettyLauncher$WebAppContextWithReload.doStart(JettyLauncher.java:468)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.handler.RequestLogHandler.doStart(RequestLogHandler.java:115)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:222)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at com.google.gwt.dev.shell.jetty.JettyLauncher.start(JettyLauncher.java:672)
	at com.google.gwt.dev.DevMode.doStartUpServer(DevMode.java:509)
	at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:1068)
	at com.google.gwt.dev.DevModeBase.run(DevModeBase.java:811)
	at com.google.gwt.dev.DevMode.main(DevMode.java:311)
Caused by: java.lang.ClassNotFoundException: javax.servlet.AsyncListener
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.mortbay.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:352)
	at org.mortbay.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:337)
	... 25 more
```

I googled a bit about that error, and it seems that AsyncListener is an interface introduced in Java Servlet API 3.0, while we're still on 2.5 according to our [web.xml](https://github.com/eclipse/kapua/blob/develop/console/src/main/webapp/WEB-INF/web.xml)

**Comment by lorthirk** [comment]
I forgot to mention, this happens while running the Console application in Eclipse (Debug As -> Web Application)
